name: 'linear-status-action'
description: 'Updates Linear ticket status based on PRs'
author: 'Switchboard Visual Technologies'
inputs:
  pr-ids: # change this
    required: true
    description: 'Array of pull request identifiers (as a JSON string)'
    default: '[]'
runs:
  using: 'node16'
  main: 'dist/index.js'
