name: 'linear-status-action'
description: 'Updates Linear ticket status based on PRs'
author: 'Switchboard Visual Technologies'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node16'
  main: 'dist/index.js'
